/** Translate known registry prose at presentation time; unknown/new descriptions remain visible. */
const COPY: Record<string, string> = {
  "Natural language proposal": "自然语言提案",
  "LLM + parse": "模型调用与解析",
  "Graph integrity": "图结构完整性",
  "Reachability / witness path": "可达性与见证路径",
  "Heuristic spec compiler": "启发式规格编译",
  "Semantic constraint check": "语义约束检查",
  "Type / producer-consumer dataflow": "类型与生产消费数据流",
  "Safety policy heuristics": "安全策略风险检测",
  "Temporal monitor": "时序约束监视",
  "Partial-order trace alignment": "偏序运行轨迹对齐",
  "Impact-set incremental verify": "基于影响集合的增量验证",
  "Patch guard": "补丁守卫",
  "Lexicographic candidate selection": "字典序候选选择",
  "Minimized counterexample": "反例最小化",
  "Ground-truth IR mutation": "带真值标签的工作流变异",
  "NL → IR compiler": "自然语言工作流编译",
  "Whitelist, on_fail, guard AST, dead nodes.": "检查节点白名单、失败处理、守卫语法树与不可达节点。",
  "BFS shortest path and bounded DFS paths_to for ordering and missing-gate witnesses.": "使用广度优先最短路径与有界深度优先搜索，为顺序违规及缺失审题门提供见证路径。",
  "NL keywords to WorkflowSpec. Default path does not call an LLM.": "将自然语言关键词编译为工作流规格，默认流程不调用大模型。",
  "Required actions, ordering, data dependencies against the IR.": "对照工作流中间表示，检查必要动作、执行顺序和数据依赖。",
  "Edge in_type/out_type mismatch plus spec producer→consumer reachability.": "检查连边输入输出类型是否匹配，以及规格要求的生产者到消费者是否可达。",
  "Human gate, bounds, hardcoded secrets, unrestricted webhook keys.": "检查人工审题门、数据边界、硬编码密钥与未受限制的 webhook 密钥。",
  "Deterministic one-pass monitor for a temporal subset (not LTL).": "对有限时序约束子集执行确定性单遍监视，不是完整的线性时序逻辑验证。",
  "Align expected poset vs observed sequence with DP edit distance plus happens-before.": "结合动态规划编辑距离与先后关系，将预期偏序和实际观测序列对齐。",
  "Diff IR, compute downstream impact, re-run affected verifiers; topology falls back to full.": "比较工作流差异，计算下游影响并重跑相关验证器；拓扑变化时回退完整验证。",
  "Pre/post conditions on Patch DSL. Illegal patches never apply.": "检查补丁描述语言的前置与后置条件，不应用非法补丁。",
  "K≤3 plans, incremental screen, full verify, lex key, rollback on regression.": "最多生成 3 个方案，依次经过增量筛查、完整验证和字典序选择，发现退化则回滚。",
  "Witness-path + affected-node slice. Approximate, not globally minimal.": "基于见证路径和受影响节点生成近似反例切片，不保证全局最小。",
  "Inject labeled faults. Mutants that do not change IR are rejected.": "注入带标签的故障，并拒绝未实际改变工作流的变异样本。",
  "Optional DeepSeek JSON compile with keyword fallback. Not used for pass/fail.": "可选用 DeepSeek 生成工作流 JSON，失败时回退关键词规则；模型不决定通过或失败。",
  "Compose-domain whitelist; not a general n8n node catalog.": "白名单仅覆盖出题领域，不是通用 n8n 节点目录。",
  "Does not enumerate all paths on dense DAGs.": "不会枚举稠密有向无环图中的全部路径。",
  "Heuristic templates. LLM IR generation is a separate optional compiler.": "采用启发式模板；大模型生成工作流是独立的可选编译流程。",
  "Selectors match id/kind/tool; no full first-order logic.": "选择器按节点编号、类型或工具匹配，不支持完整一阶逻辑。",
  "Not a taint graph. No field-level slicing.": "不是污点分析图，不支持字段级切片。",
  "Risk detection, not a proof. Not full taint to EXTERNAL_SINK.": "提供风险检测，不构成安全证明，也不是针对外部接收端的完整污点分析。",
  "Mock traces unless n8n env is set. UNKNOWN when a branch is not observed.": "未配置 n8n 环境时使用模拟轨迹；未观测到分支时返回未知状态。",
  "Not Petri-net process mining. One linear extension for display. Approximate concurrent matching.": "不属于 Petri 网过程挖掘；展示采用一种线性扩展，并发匹配为近似结果。",
  "Node add/remove uses full verification on purpose.": "增加或删除节点时使用完整验证。",
  "Guards structural preconditions, not semantic optimality.": "守卫检查结构前提，不保证语义最优。",
  "Planner is rule-based. Optional LLM compile is a different path.": "规划器基于规则，可选的大模型编译属于独立流程。",
  "Does not claim mathematical minimality. Delta-debugging is one pass of drop-non-witness nodes.": "不声称数学意义上的最小性；差分调试采用单轮删除非见证节点的策略。",
  "In-repo gold IR only. Not an external leaderboard.": "仅使用仓库内部标准工作流，不代表外部排行榜成绩。",
  "Fallback examples when no API key. Verification remains deterministic.": "未配置接口密钥时回退示例流程，验证仍采用确定性规则。",
  "Walk nodes": "遍历节点", "Apply structural rules": "应用结构规则", "Emit CheckError": "输出结构错误",
  "Sources by indegree 0": "选择入度为零的起点", "BFS / bounded DFS": "广度优先 / 有界深度优先搜索", "Return path": "返回路径",
  "Build happens-before from IR edges and spec BEFORE constraints": "由工作流连边与规格先后约束建立先发生关系",
  "Kahn linear extension biased by observed order": "结合观测顺序，用 Kahn 算法生成线性扩展",
  "Needleman–Wunsch / edit DP on expected vs observed ids": "使用 Needleman–Wunsch 编辑距离动态规划，对齐预期与观测节点",
  "Relabel HB violations as OUT_OF_ORDER; incomparable pairs stay MATCH": "将先后关系违规标为乱序，不可比较的节点对保留匹配状态",
  "gen → pub is reachable without human_gate → witness.": "gen → pub 可绕过 human_gate 到达发布节点，该路径即为见证。",
  "Expected Schedule HTTP IF Email vs Observed Schedule HTTP Email → IF MISSING_EXPECTED.": "预期为 Schedule → HTTP → IF → Email，实际为 Schedule → HTTP → Email，检测出缺失 IF 节点。",
  "O(V+E) plus guard parse": "O(V+E)，另加守卫解析开销",
  "BFS O(V+E); mandatory-checkpoint avoidance O(V+E)": "广度优先搜索 O(V+E)；绕过必经节点检查 O(V+E)",
  "O(E) types + O(|D|·(V+E)) deps": "类型检查 O(E)；依赖检查 O(|D|·(V+E))",
  "O(V^2) reachability + O(n·m) DP": "可达性 O(V²)；动态规划 O(n·m)",
  "O(V+E) diff/impact + subset of full verify": "差异与影响计算 O(V+E)，加上相关验证子集的开销",
  "O(V+E) slice": "切片 O(V+E)",
};

export function algorithmCopy(text: string) {
  return COPY[text] || text;
}
